### ISSUE TITLE
加载js,layer.js报错

### ISSUE THREAD

**Issue by ymayx** [wangerzi/layui-authtree#1]
TypeError: l.push is not a function[详细了解]

**Comment by ymayx** [comment]
是因为和Js冲突呀

**Comment by wangerzi** [comment]
是哪个文件报的错啊？layer.js？还是authtree.js？

**Comment by wangerzi** [comment]
如果依旧有问题的话可以再留言，我先把这个 ISSUE 关掉，放着很久了。
