### ISSUE TITLE
兼容ie8吗

### ISSUE THREAD

**Issue by lintiansheng** [wangerzi/layui-authtree#10]

**Comment by wangerzi** [comment]
之前不可以，现在可以了。
之前：
![image](https://user-images.githubusercontent.com/22190579/48298752-88560e00-e4fd-11e8-9eaf-0ff7da7b6d9f.png)
现在：
![image](https://user-images.githubusercontent.com/22190579/48298756-99068400-e4fd-11e8-9f83-07552805d22a.png)
