### ISSUE TITLE
全选和全不选在火狐浏览器控制台报错

### ISSUE THREAD

**Issue by amx006** [wangerzi/layui-authtree#19]
// 自动刷新多选框半选状态
		autoNodeRender: function(dst) {
			var tree = this.getRenderedInfo(dst);
			var opt = tree.opt;
			if (opt.halfchoose) {
				this._nodeRenderByParent($(dst).find('.auth-single'))
			}
			document.styleSheets[0].addRule(dst + ' .layui-icon-ok:before', 'content: '+this.checkedIconContent)
		},

火狐浏览器不兼容  document.styleSheets[0].addRule 的写法。

修改为如下方式即可兼容火狐浏览器对样式的修改。
// 自动刷新多选框半选状态
		autoNodeRender: function(dst) {
			var tree = this.getRenderedInfo(dst);
			var opt = tree.opt;
			if (opt.halfchoose) {
				this._nodeRenderByParent($(dst).find('.auth-single'))
			}
			try{
				document.styleSheets[0].addRule(dst + ' .layui-icon-ok:before', 'content: '+this.checkedIconContent)
			}catch(e){
				 var rule=dst + ' .layui-icon-ok:before{content: '+this.checkedIconContent+"}";
				 var index=document.styleSheets[0].cssRules.length;
				 document.styleSheets[0].insertRule(rule, index); 
			}
		},

**Comment by wangerzi** [comment]
感谢反馈，之前调试半选状态的代码，有点问题已经先行屏蔽了
