### ISSUE TITLE
关于prefixChildStr的层级

### ISSUE THREAD

**Issue by xiaoguo0426** [wangerzi/layui-authtree#24]
![image](https://user-images.githubusercontent.com/8944962/71962589-ba175180-3234-11ea-9fed-636f86e83399.png)
`用户管理`下的权限与其平级，不是很能直观表现其上下级关系。
建议修改`authtree.js`的`291`行，
![image](https://user-images.githubusercontent.com/8944962/71962717-08c4eb80-3235-11ea-8e71-073489572779.png)
修改后的效果为
![image](https://user-images.githubusercontent.com/8944962/71962753-22663300-3235-11ea-8cc9-227a966a074d.png)

**Comment by wangerzi** [comment]
这个我做成配置可选吧，因为有些使用者会喜欢精简一点的，感谢反馈~
