### ISSUE TITLE
数据源接口建议

### ISSUE THREAD

**Issue by adminpass** [wangerzi/layui-authtree#4]
建议使用类似ztree数组结构，tree.json里是嵌套接口，后台一般数据库查询返回的都是List，还需要在后台单独写递归循环组装成嵌套接口，模块多的话，很费事

**Comment by wangerzi** [comment]
感谢反馈，后期考虑添加一个处理 list 数据的方法，方便使用！

**Comment by MrZhouL** [comment]
这个控件是不更新了吗。list数据处理方法还添加吗。用起来是真的不方便。。。

**Comment by wangerzi** [comment]
正在写这个功能，进行顺利的话今天就能推过去。

**Comment by wangerzi** [comment]
v1.1 已更新，涵盖 自动展开所有选中节点、列表结构转树结构、双击展开子节点、自动选中/自动取消开关等
