### ISSUE TITLE
关于数据回显

### ISSUE THREAD

**Issue by Githubbili** [wangerzi/layui-authtree#5]
回显后，子节点勾上但是父节点没有自动勾选。然后想请问一下，如果点击全选时，全部节点自动勾上，反选则取消全选？如何点击已选择按钮时，只显示已选择的权限。还有点击未选择的，可以显示没有选中的节点。

**Comment by wangerzi** [comment]
那个，回显是什么意思呢？全选和未全选的逻辑在 v1.0改了一下，可以先看看新版本有没有什么问题。

**Comment by wangerzi** [comment]
如果是希望选中或取消后触发获取各种状态的节点，目前提供的方法可以其实现，具体可以参考文档和最新官方样例。
