### ISSUE TITLE
在不选中任何兄弟节点情况下，取消全选失败！

### ISSUE THREAD

**Issue by jo-jordan** [wangerzi/layui-authtree#8]
在不选中任何兄弟节点情况下，单独选中一个根节点，然后接着取消，改节点下面的所有节点不会取消选中状态，并且Console中报错：

`jquery-3.3.1.min.js:2 Uncaught RangeError: Maximum call stack size exceeded`
`   at Function.get [Symbol.species] (<anonymous>)`
`    at Array.concat (<anonymous>)`
`   at Function.map (jquery-3.3.1.min.js:2)`
`    at w.fn.init.w.fn.(anonymous function) [as parent] (http://127.0.0.1:8080/common/js/jquery-3.3.1.min.js:2:26996)`
`    at Object._autoclose (authtree.js?v=1539173846283:134)`
`    at Object._autoclose (authtree.js?v=1539173846283:139)`
`    at Object._autoclose (authtree.js?v=1539173846283:139)`
`    at Object._autoclose (authtree.js?v=1539173846283:139)`
`    at Object._autoclose (authtree.js?v=1539173846283:139)`
`    at Object._autoclose (authtree.js?v=1539173846283:139)`

不知是我环境的问题还是什么，下面这行代码注释掉一切正常，只是可能不能自动收回下一级节点。
https://github.com/wangerzi/layui-authtree/blob/019d0d50ee0706a1b5a426c8ac003d4c018a667d/extends/authtree.js#L139

Google Chrome 已是最新版本
版本 69.0.3497.100（正式版本） （64 位）

没用其他浏览器测试。

其他的都很棒！感谢。

**Comment by wangerzi** [comment]
不好意思，忘了看这边的issue，我抽空找找问题。

**Comment by wangerzi** [comment]
全部取消的逻辑已经改过了，目前也没有测出来有这个问题，感谢反馈！！！
