### ISSUE TITLE
菜单中数据过多时点选造作耗时很长

### ISSUE THREAD

**Issue by MrPanNo1** [wangerzi/layui-authtree#9]
大约有150个数据 很卡顿

**Comment by wangerzi** [comment]
感谢反馈，我先看看具体原因！

**Comment by wangerzi** [comment]
150个数据很卡顿，是不是把所有事件都监听了呢？官方样例为了达到展示效果，所以监听之后，会触发大量的回调来打印数据，将回调中的 console.log() 去掉试试看有没有这么卡呢？

**Comment by 185510765** [comment]
我这接近200个节点 不卡啊
